### PR TITLE
Fix #24 (Refactor the whole repo update logic).

### LINKED ISSUE #24: Wrong 'failed repo' list in certain situations
In the example below (from an actual run on my own local repos), it will list 2 repos as failed, while in fact they are both the same one :   
````
* Checking /media/Repo/git-others/atom-stuff/linter (https://github.com/atom-community/linter.git)
   error: Pulling is not possible because you have unmerged files.
   fatal: Exiting because of an unresolved conflict.
````
This gives : 
```
!! Note : The following 2 repositories FAILED during this run :
  [x] /media/Repo/git-others/atom-stuff/linter (https://github.com/atom-community/linter.git)
    -> "error: Pulling is not possible because you have unmerged files."
  [x] /media/Repo/git-others/atom-stuff/linter (https://github.com/atom-community/linter.git)
    -> "fatal: Exiting because of an unresolved conflict."
```

This is because both the `error:` and `fatal:` will be logged. We check for both since different faults give one or the other. It now seems possible to get both.

__However__, the failed count is correct so fault lies in the method to add the failure to the Array Can probably be fixed be removing any duplicate URL or path from the array either at the time or before printing out.

### PR DESCRIPTION
**Pull request by seapagan**
Now the script will not change directory before each git operation, we instead take advantage of the Git '-C' flag that allows us to perform the operation on a repo in a completely different directory. Note however that this needs Git version >= 1.8.5. Commit e7b2bf2 in this PR will check for this at script start up and fail gracefully if the version is too low. Should not be too much of an issue since most systems have a more recent version.

I have also removed the use of separate threads for stdout and stderr, and consolidated the display into a single function. As a result of this, we no longer get thread race conditions where the local directory may have been changed by a separate thread causing erroneous directories to be reported in the fail list.
This is the main factor to now getting consistent outputs over consecutive runs. This may generally make the whole script a little more stable but that needs more runs to be sure.

As the main purpose of this PR, it fixes issue #24 - Duplicates in the footer error list when a pull fails with both `error:` and `fatal:` messages

This commit also fixes a bug introduced by a previous commit that caused the
--dump and --dump-remotes to fail.

### CODE REVIEW

**Comment by seapagan** [comment]
[PullReview stats](https://www.pullreview.com/github/seapagan/update_repo/reviews/hotfix-issue-24)

File: lib/update_repo.rb [hunk 1]
```diff
@@ -139,7 +146,7 @@ def update_repo(dirname)
     def dump_repo(dir)
       Dir.chdir(dir.chomp!('/')) do
         print_log "#{trunc_dir(dir, config['cmd'][:prune])}," if cmd(:dump)
-        print_log "#{get_repo_url}\n"
+        print_log `git -C #{dir} config remote.origin.url`
```
Comment (seapagan) [inline lib/update_repo.rb]: The function 'get_repo_url' had been removed in a previous commit somehow, causing the --dump and --dump-remote commands to fail. This patch fixes that

**Comment by seapagan** [comment]
[PullReview](https://www.pullreview.com/github/seapagan/update_repo/reviews/hotfix-issue-24?to_sha=98ceae751832145ef8083afea9b3af686c117e53) **[1 to go.](https://www.pullreview.com/github/seapagan/update_repo/reviews/hotfix-issue-24)**

**Comment by seapagan** [comment]
[PullReview](https://www.pullreview.com/github/seapagan/update_repo/reviews/hotfix-issue-24?to_sha=7f3291bc2e4c94f08b4d7c81045fb64627682262) **[Great just fixed 2 issues,  1 to go.](https://www.pullreview.com/github/seapagan/update_repo/reviews/hotfix-issue-24)**
[Code smell](https://www.pullreview.com/github/seapagan/update_repo/reviews/hotfix-issue-24) Avoid assignment in conditional.[ `lib/update_repo/git_control.rb:54`](https://www.pullreview.com/github/seapagan/update_repo/reviews/hotfix-issue-24)
[Code smell](https://www.pullreview.com/github/seapagan/update_repo/reviews/hotfix-issue-24) Reduce the number of parameters.[ `UpdateRepo::GitControl#update`](https://www.pullreview.com/github/seapagan/update_repo/reviews/hotfix-issue-24)

**Comment by seapagan** [comment]
[PullReview](https://www.pullreview.com/github/seapagan/update_repo/reviews/hotfix-issue-24?to_sha=9d1610c50df19ef092893a119c459802d582b464) **[1 to go.](https://www.pullreview.com/github/seapagan/update_repo/reviews/hotfix-issue-24)**

**Comment by seapagan** [comment]
[PullReview](https://www.pullreview.com/github/seapagan/update_repo/reviews/hotfix-issue-24?to_sha=4f46884438234c28624ba821494746817d57b086) **[1 to go.](https://www.pullreview.com/github/seapagan/update_repo/reviews/hotfix-issue-24)**

**Comment by seapagan** [comment]
[PullReview](https://www.pullreview.com/github/seapagan/update_repo/reviews/hotfix-issue-24?to_sha=e7b2bf2f6dceb9a95712091e674e9d7a0f040fc0) **[2 to go.](https://www.pullreview.com/github/seapagan/update_repo/reviews/hotfix-issue-24)**

File: lib/update_repo.rb [hunk 2]
```diff
@@ -50,6 +53,18 @@ def start
 
     private
 
+    def checkgit
+      unless which('git')
+        puts 'Git is not installed on this machine, script cannot continue.'.red
```
Comment (seapagan) [inline lib/update_repo.rb]: [Code smell](https://www.pullreview.com/github/seapagan/update_repo/reviews/hotfix-issue-24) Use a logger instead of puts or add assertion.[ `UpdateRepo::WalkRepo#checkgit`](https://www.pullreview.com/github/seapagan/update_repo/reviews/hotfix-issue-24)

**Comment by seapagan** [comment]
[PullReview](https://www.pullreview.com/github/seapagan/update_repo/reviews/hotfix-issue-24?to_sha=ac302bb36fcf201bbf261104ce8840ae9fda40e3) **[2 to go.](https://www.pullreview.com/github/seapagan/update_repo/reviews/hotfix-issue-24)**

**Comment by seapagan** [comment]
[PullReview](https://www.pullreview.com/github/seapagan/update_repo/reviews/hotfix-issue-24?to_sha=30dba09552f731d83d2f648f430ba34ea37e007b) **[Great just fixed 1 issue,  1 to go.](https://www.pullreview.com/github/seapagan/update_repo/reviews/hotfix-issue-24)**
[Code smell](https://www.pullreview.com/github/seapagan/update_repo/reviews/hotfix-issue-24) Use a logger instead of puts or add assertion.[ `UpdateRepo::WalkRepo#checkgit`](https://www.pullreview.com/github/seapagan/update_repo/reviews/hotfix-issue-24)

File: lib/update_repo/console_output.rb [hunk 3]
```diff
@@ -70,21 +70,23 @@ def print_metrics
     # @param [none]
     # @return [void]
     def list_failures
-      print_log "\n\n!! Note : The following #{@metrics[:failed_list].count}",
-                ' repositories ', 'FAILED'.red.underline, ' during this run :'
       # ensure we don't have duplicate errors from the same repo
-      # @metrics[:failed_list].uniq! { |x| x[:loc] }
       remove_dups
```
Comment (seapagan) [inline lib/update_repo/console_output.rb]: Move this function to the top of the function or the second __count__ of failed is wrong above the list even though the duplicate is removed before display
